[env:esp32s_cam]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    https://github.com/espressif/esp32-camera

board_build.partitions = huge_app.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

upload_resetmethod = nodemcu